#!/bin/bash
#PBS -P xe2
#PBS -q copyq
#PBS -l ncpus=1
#PBS -l walltime=10:00:00
#PBS -l other=gdata1
#PBS -l mem=2G
#PBS -l wd
#PBS -o /g/data1a/xe2/phenomics/datamanagement-workspace/logs/tarball-gigavision/
#PBS -e /g/data1a/xe2/phenomics/datamanagement-workspace/logs/tarball-gigavision/
#PBS -m abe
#PBS -M pbs@kdmurray.id.au,m6b6j7n4m7x0o5x6@bvz-traitcapture.slack.com
#PBS -W umask=002

WORKDIR=/g/data/xe2/phenomics/datamanagement-workspace
THIS_SCRIPT=$WORKDIR/code/datamgmt/tarball-gigavision.pbs
CAMUPLOAD=/g/data/xe2/phenomics/camupload

# Self-submit?
NEXT=$(qsub -W depend=afterany:$PBS_JOBID "$THIS_SCRIPT")

# Self-submit?
if [ -n "${NEXT:-}" ]
then
    qdel $NEXT
fi
